param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectName,
    
    [Parameter(Mandatory=$false)]
    [string]$TemplateType = "full-stack"
)

$ErrorActionPreference = "Stop"
$baseDir = Split-Path $PSScriptRoot -Parent
$projectsDir = Join-Path $baseDir "projects"
$projectDir = Join-Path $projectsDir $ProjectName

Write-Host "=== Creating project: $ProjectName ===" -ForegroundColor Cyan
Write-Host "Template: $TemplateType" -ForegroundColor Yellow

if (Test-Path $projectDir) {
    Write-Host "ERROR: Project directory already exists: $projectDir" -ForegroundColor Red
    exit 1
}

New-Item -ItemType Directory -Path $projectDir -Force | Out-Null
Write-Host "Created: $projectDir" -ForegroundColor Green

switch ($TemplateType) {
    "full-stack" {
        $dirs = @("src\frontend", "src\backend", "src\shared", "tests", "docs", "scripts")
        foreach ($d in $dirs) {
            New-Item -ItemType Directory -Path (Join-Path $projectDir $d) -Force | Out-Null
        }
        $readme = @"
# $ProjectName

## Stack
- Frontend: TBD
- Backend: TBD
- Database: TBD

## Quick Start
``````bash
# Frontend
cd src/frontend
npm install
npm run dev

# Backend
cd src/backend
pip install -r requirements.txt
python main.py
``````

## Structure
``````
src/
├── frontend/
├── backend/
├── shared/
tests/
docs/
scripts/
``````

## Commands
- `/status` - Check project status
- `/sync` - Sync context from Memory Bank

---
Generated by agent-hq
"@
        Set-Content -Path (Join-Path $projectDir "README.md") -Value $readme
    }
    "api-only" {
        $dirs = @("src\api", "src\models", "tests", "docs")
        foreach ($d in $dirs) {
            New-Item -ItemType Directory -Path (Join-Path $projectDir $d) -Force | Out-Null
        }
        $readme = @"
# $ProjectName

## Stack
- API: TBD
- Database: TBD

## Quick Start
``````bash
cd src/api
pip install -r requirements.txt
python main.py
``````

## API Endpoints
- `GET /health` - Health check
- `POST /api/v1/` - TBD

---
Generated by agent-hq
"@
        Set-Content -Path (Join-Path $projectDir "README.md") -Value $readme
    }
    "mobile" {
        $dirs = @("src\app", "src\components", "src\screens", "tests")
        foreach ($d in $dirs) {
            New-Item -ItemType Directory -Path (Join-Path $projectDir $d) -Force | Out-Null
        }
        $readme = @"
# $ProjectName

## Stack
- Framework: React Native / Flutter
- State: TBD

## Quick Start
``````bash
npm install
npx expo start
``````

---
Generated by agent-hq
"@
        Set-Content -Path (Join-Path $projectDir "README.md") -Value $readme
    }
    "data-pipeline" {
        $dirs = @("src\etl", "src\transforms", "src\models", "tests", "configs")
        foreach ($d in $dirs) {
            New-Item -ItemType Directory -Path (Join-Path $projectDir $d) -Force | Out-Null
        }
        $readme = @"
# $ProjectName

## Stack
- Orchestration: Airflow / Prefect
- Processing: Spark / Pandas
- Storage: TBD

## Quick Start
``````bash
cd src/etl
python pipeline.py
``````

---
Generated by agent-hq
"@
        Set-Content -Path (Join-Path $projectDir "README.md") -Value $readme
    }
    default {
        Write-Host "Unknown template: $TemplateType. Using full-stack." -ForegroundColor Yellow
    }
}

$gitignore = @"
node_modules/
__pycache__/
*.pyc
.venv/
venv/
dist/
build/
.env
.env.local
*.log
.DS_Store
Thumbs.db
"@
Set-Content -Path (Join-Path $projectDir ".gitignore") -Value $gitignore

Write-Host ""
Write-Host "=== Project created: $projectDir ===" -ForegroundColor Green
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. cd $projectDir" -ForegroundColor White
Write-Host "  2. git init && git add -A && git commit -m 'init'" -ForegroundColor White
Write-Host "  3. Start coding!" -ForegroundColor White
